import { join } from 'node:path';
import { getPackageRoot } from '../paths.js';

/** Filename used for the thin hook shim (Claude global + project-level agents). */
export const HOOK_FILENAME = 'starlog-pkg-check.js';

/**
 * Generate the thin shim that resolves dist/hook-runner.js from the installed package.
 * Upgrading starloghq refreshes hook behaviour with no re-init.
 */
export function generateHookScript(): string {
  const bakedPath = join(getPackageRoot(), 'dist', 'hook-runner.js');
  return `#!/usr/bin/env node
// starlog-pkg-check.js — agent hook dispatcher (thin shim)
// Generated by: starlog init
// Routes PreToolUse Write|Edit|MultiEdit (DIY detect) and install-vet events.
// Real logic lives in dist/hook-runner.js — upgrades refresh behaviour with NO
// need to re-run \`starlog init\`. Advisory by default.
const url = require('url');
const candidates = [];
try { candidates.push(require.resolve('starloghq/dist/hook-runner.js')); } catch (e) { /* not installed as a local dep */ }
candidates.push(${JSON.stringify(bakedPath)});
(async () => {
  for (const c of candidates) {
    try {
      const mod = await import(url.pathToFileURL(c).href);
      if (mod && typeof mod.run === 'function') { mod.run(); return; }
    } catch (e) { /* try next candidate */ }
  }
  process.exit(0); // nothing resolved — never block a tool call
})();
`;
}
