import type { L2Overlay } from '@starloghq/facts-schema';

/**
 * Public L2 overlay (hand-authored stand-in for the future OSV/deps.dev pull).
 * Reputation/vuln/license/maintenance only — NO effect_surface (that is L1).
 * Freshness lives in attestation.fetched_at; source is 'hand' until osvL2Source
 * is built (see l2-source.ts). The original citations live in attestation.refs.
 */
const FETCHED = '2026-06-01';

export const L2_OVERLAYS_LIST: L2Overlay[] = [
  {
    package: 'xz-utils',
    ecosystem: 'system',
    known_vulns: [
      {
        id: 'CVE-2024-3094',
        severity: 'critical',
        affected: '5.6.0, 5.6.1',
        summary:
          'Malicious backdoor planted in upstream release tarballs by a maintainer; allows remote unauthenticated code execution via crafted SSH. CVSS 10.0.',
      },
    ],
    license: 'GPL-2.0-or-later',
    license_risk: 'copyleft-strong',
    maintenance: 'compromised',
    transitive_risk: 'Pulled transitively by build tooling that links liblzma.',
    attestation: { source: 'hand', refs: ['NVD CVE-2024-3094', 'oss-security 2024-03-29 (A. Freund)'], fetched_at: FETCHED },
  },
  {
    package: 'event-stream',
    ecosystem: 'npm',
    known_vulns: [
      {
        id: 'INCIDENT:event-stream-flatmap-2018',
        severity: 'critical',
        affected: '3.3.6 (via flatmap-stream@0.1.1)',
        summary:
          'After a maintainer handoff, a malicious transitive dep (flatmap-stream) was added that targeted Copay bitcoin-wallet builds to exfiltrate credentials.',
      },
    ],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'abandoned',
    transitive_risk: 'The payload lived in the transitive dep flatmap-stream, not event-stream itself.',
    attestation: { source: 'hand', refs: ['npm/GitHub advisory 2018', 'Snyk, npm blog'], fetched_at: FETCHED },
  },
  {
    package: 'ua-parser-js',
    ecosystem: 'npm',
    known_vulns: [
      {
        id: 'INCIDENT:ua-parser-js-2021',
        severity: 'critical',
        affected: '0.7.29, 0.8.0, 1.0.0',
        summary:
          'Maintainer account hijacked (Oct 2021); these versions shipped a password stealer and cryptominer. Treat installs as account-compromise.',
      },
    ],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: 'Frequently a transitive dep — pin away from the three bad versions.',
    attestation: { source: 'hand', refs: ['GitHub Security Advisory', 'CISA alert Oct 2021'], fetched_at: FETCHED },
  },
  {
    package: 'node-ipc',
    ecosystem: 'npm',
    known_vulns: [
      {
        id: 'CVE-2022-23812',
        severity: 'high',
        affected: '10.1.1, 10.1.2',
        summary:
          'Maintainer "protestware" (peacenotwar): overwrote/wiped files on hosts geolocated to Russia/Belarus. Intentional sabotage by the author.',
      },
    ],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'compromised',
    transitive_risk: 'Pulled transitively by some popular packages at the time.',
    attestation: { source: 'hand', refs: ['NVD CVE-2022-23812'], fetched_at: FETCHED },
  },
  {
    package: 'colors',
    ecosystem: 'npm',
    known_vulns: [
      {
        id: 'INCIDENT:colors-faker-sabotage-2022',
        severity: 'medium',
        affected: '1.4.44-liberty-2',
        summary:
          'Maintainer self-sabotage (Jan 2022): introduced an infinite loop printing garbage, breaking any app importing it (DoS).',
      },
    ],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'compromised',
    transitive_risk: 'Extremely common transitive dep.',
    attestation: { source: 'hand', refs: ['Bleeping Computer, GitHub (Jan 2022)'], fetched_at: FETCHED },
  },
  {
    package: 'request',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'Apache-2.0',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'hand', refs: ['request#3142 (deprecated Feb 2020)'], fetched_at: FETCHED },
  },
  {
    package: 'moment',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'maintenance-only',
    transitive_risk: null,
    attestation: { source: 'hand', refs: ['momentjs.com project-status'], fetched_at: FETCHED },
  },
  {
    package: 'left-pad',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'WTFPL',
    license_risk: 'none',
    maintenance: 'abandoned',
    transitive_risk: null,
    attestation: { source: 'hand', refs: ['2016 unpublish incident (cautionary)'], fetched_at: FETCHED },
  },
  {
    package: 'grafana',
    ecosystem: 'system',
    known_vulns: [],
    license: 'AGPL-3.0-only',
    license_risk: 'copyleft-strong',
    maintenance: 'active',
    transitive_risk:
      'Relicensed Apache-2.0 → AGPL-3.0 at v8 (2021). Forking/modifying a self-hosted, network-served closed-source product can trigger AGPL source-disclosure.',
    attestation: { source: 'hand', refs: ['Grafana Labs relicense announcement 2021'], fetched_at: FETCHED },
  },
  {
    package: 'chalk',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'hand', refs: ['Active, permissive, no known advisories'], fetched_at: FETCHED },
  },
  {
    package: 'date-fns',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'hand', refs: ['Active, permissive, no known advisories'], fetched_at: FETCHED },
  },
  {
    package: 'lucia',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/lucia/3.2.2'], fetched_at: '2026-06-04' },
  },
  {
    package: 'passport-jwt',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'maintenance-only',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/passport-jwt/4.0.1'], fetched_at: '2026-06-04' },
  },
  {
    package: 'csurf',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/csurf/1.11.0'], fetched_at: '2026-06-04' },
  },
  {
    package: 'launchdarkly-node-server-sdk',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'Apache-2.0',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/launchdarkly-node-server-sdk/7.0.4'], fetched_at: '2026-06-04' },
  },
  {
    package: 'posthog-node',
    ecosystem: 'npm',
    known_vulns: [
      { id: 'MAL-2025-190925', severity: 'medium', affected: '5.11.3, 5.13.3, 4.18.1', summary: 'Historical supply-chain incident — pin away from the affected versions. Malicious code in posthog-node (npm)' }
    ],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'osv', refs: ['https://deps.dev/npm/posthog-node/5.35.14', 'https://osv.dev/vulnerability/MAL-2025-190925'], fetched_at: '2026-06-04' },
  },
  {
    package: 'node-cache',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'maintenance-only',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/node-cache/5.1.2'], fetched_at: '2026-06-04' },
  },
  {
    package: 'socket.io',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/socket.io/4.8.3'], fetched_at: '2026-06-04' },
  },
  {
    package: 'sockjs',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'maintenance-only',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/sockjs/0.3.24'], fetched_at: '2026-06-04' },
  },
  {
    package: 'kue',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'maintenance-only',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/kue/0.11.6'], fetched_at: '2026-06-04' },
  },
  {
    package: 'bottleneck',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'maintenance-only',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/bottleneck/2.19.5'], fetched_at: '2026-06-04' },
  },
  {
    package: 'nodemailer',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT-0',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/nodemailer/8.0.10'], fetched_at: '2026-06-04' },
  },
  {
    package: 'prisma',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'Apache-2.0',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/prisma/7.8.0'], fetched_at: '2026-06-04' },
  },
  {
    package: 'request-promise',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'ISC',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/request-promise/4.2.6'], fetched_at: '2026-06-04' },
  },
  {
    package: 'node-sass',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/node-sass/9.0.0'], fetched_at: '2026-06-04' },
  },
  {
    package: 'faker',
    ecosystem: 'npm',
    known_vulns: [
      { id: 'GHSA-5w9c-rv96-fr7g', severity: 'high', affected: '6.6.6', summary: 'Removal of functional code in faker.js' }
    ],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'maintenance-only',
    transitive_risk: null,
    attestation: { source: 'osv', refs: ['https://deps.dev/npm/faker/6.6.6', 'https://osv.dev/vulnerability/GHSA-5w9c-rv96-fr7g'], fetched_at: '2026-06-04' },
  },
  {
    package: 'bower',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'maintenance-only',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/bower/1.8.14'], fetched_at: '2026-06-04' },
  },
  {
    package: 'istanbul',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'BSD-3-Clause',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/istanbul/0.4.5'], fetched_at: '2026-06-04' },
  },
  {
    package: 'tslint',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'Apache-2.0',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/tslint/6.1.3'], fetched_at: '2026-06-04' },
  },
  {
    package: 'protractor',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/protractor/7.0.0'], fetched_at: '2026-06-04' },
  },
  {
    package: 'node-uuid',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'UNKNOWN',
    license_risk: 'unknown',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/node-uuid/1.4.8'], fetched_at: '2026-06-04' },
  },
  {
    package: 'q',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/q/1.5.1'], fetched_at: '2026-06-04' },
  },
  {
    package: 'bluebird',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'maintenance-only',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/bluebird/3.7.2'], fetched_at: '2026-06-04' },
  },
  {
    package: 'coffee-script',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/coffee-script/1.12.7'], fetched_at: '2026-06-04' },
  },
  {
    package: 'mkdirp',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'maintenance-only',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/mkdirp/3.0.1'], fetched_at: '2026-06-04' },
  },
  {
    package: 'babel-eslint',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/babel-eslint/10.1.0'], fetched_at: '2026-06-04' },
  },
  {
    package: 'har-validator',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'deprecated',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/har-validator/5.1.5'], fetched_at: '2026-06-04' },
  },
  {
    package: 'lodash',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/lodash/4.18.1'], fetched_at: '2026-06-04' },
  },
  {
    package: 'axios',
    ecosystem: 'npm',
    known_vulns: [
      { id: 'MAL-2026-2307', severity: 'medium', affected: '0.30.4, 1.14.1', summary: 'Historical supply-chain incident — pin away from the affected versions. Malicious code in axios (npm)' }
    ],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'osv', refs: ['https://deps.dev/npm/axios/1.17.0', 'https://osv.dev/vulnerability/MAL-2026-2307'], fetched_at: '2026-06-04' },
  },
  {
    package: 'express',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/express/5.2.1'], fetched_at: '2026-06-04' },
  },
  {
    package: 'zod',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'deps.dev', refs: ['https://deps.dev/npm/zod/4.4.3'], fetched_at: '2026-06-04' },
  },
  {
    package: 'puppeteer',
    ecosystem: 'npm',
    known_vulns: [
      { id: 'MAL-2026-5077', severity: 'medium', affected: '25.0.1', summary: 'Historical supply-chain incident — pin away from the affected versions. Malicious code in puppeteer (npm)' }
    ],
    license: 'Apache-2.0',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'osv', refs: ['https://deps.dev/npm/puppeteer/25.1.0', 'https://osv.dev/vulnerability/MAL-2026-5077'], fetched_at: '2026-06-04' },
  },
  {
    package: '@clerk/nextjs',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'hand', refs: ['https://www.npmjs.com/package/@clerk/nextjs'], fetched_at: FETCHED },
  },
  {
    package: '@auth0/nextjs-auth0',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'hand', refs: ['https://www.npmjs.com/package/@auth0/nextjs-auth0'], fetched_at: FETCHED },
  },
  {
    package: '@supabase/supabase-js',
    ecosystem: 'npm',
    known_vulns: [],
    license: 'MIT',
    license_risk: 'none',
    maintenance: 'active',
    transitive_risk: null,
    attestation: { source: 'hand', refs: ['https://www.npmjs.com/package/@supabase/supabase-js'], fetched_at: FETCHED },
  },
];

/** package -> L2 overlay. */
export const L2_BY_PACKAGE: Record<string, L2Overlay> = Object.fromEntries(
  L2_OVERLAYS_LIST.map((o) => [o.package, o]),
);
