import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { atomicWrite } from '../fsutil.js';
import { buildL2FromInput, buildManifestFromInput, upsertL2Entry, upsertManifestEntry } from '../engine/facts/authoring.js';
import { readPatternStore, getProjectPatternsPath, updatePatternStatus } from './store.js';
import { discoverOverlay } from '../engine/overlay-discovery.js';

const DEFAULT_PRIVATE_FACTS = '.starlog/private-facts.json';
const DEFAULT_PRIVATE_CORPUS = '.starlog/private-corpus.json';

function readJsonIfPresent(path: string): unknown | null {
  try {
    return JSON.parse(readFileSync(path, 'utf-8'));
  } catch {
    return null;
  }
}

export interface PackageizeScaffoldArgs {
  patternId: string;
  packageName: string;
  solves?: string;
  projectDir?: string;
}

/**
 * Scaffold private corpus + facts entries for a packageize recommendation.
 */
export async function scaffoldPackageize(args: PackageizeScaffoldArgs): Promise<{ factsPath: string; corpusPath: string }> {
  const projectDir = args.projectDir ?? process.cwd();
  const store = await readPatternStore(getProjectPatternsPath(projectDir));
  const pattern = store.patterns.find((p) => p.id === args.patternId);
  if (!pattern) {
    throw new Error(`Pattern "${args.patternId}" not found in ${getProjectPatternsPath(projectDir)}`);
  }

  const solves =
    args.solves?.trim() ||
    `Internal ${pattern.category.replace(/-/g, ' ')} utilities extracted from repeated DIY code`;

  const manifest = buildManifestFromInput({
    package: args.packageName,
    solves,
    category: pattern.category,
    autoGenerated: true,
  });

  const overlay = buildL2FromInput({
    package: args.packageName,
    license: 'UNLICENSED',
    status: 'active',
  });

  const factsPath = discoverOverlay('private-facts.json', projectDir) ?? join(projectDir, DEFAULT_PRIVATE_FACTS);
  const corpusPath = discoverOverlay('private-corpus.json', projectDir) ?? join(projectDir, DEFAULT_PRIVATE_CORPUS);

  const factsMerged = upsertL2Entry(readJsonIfPresent(factsPath) as { l1?: unknown[]; l2?: unknown[] } | null, overlay);
  const corpusMerged = upsertManifestEntry(readJsonIfPresent(corpusPath) as { manifests?: unknown[] } | null, manifest);

  await atomicWrite(factsPath, JSON.stringify(factsMerged, null, 2) + '\n');
  await atomicWrite(corpusPath, JSON.stringify(corpusMerged, null, 2) + '\n');
  await updatePatternStatus(args.patternId, 'advised_packageize', projectDir);

  return { factsPath, corpusPath };
}
